export type MeridianStatus = "For Sale" | "For Rent";

export interface MeridianProperty {
  ref: string;
  name: string;
  /** Word rendered in italic at the end of the card name. */
  nameTail: string;
  location: string;
  city: string;
  status: MeridianStatus;
  type: string;
  /** Numeric price used for filtering and sorting. */
  price: number;
  /** Display price, e.g. "€138,000" (the "/ mo" suffix is added for rentals). */
  priceLabel: string;
  beds: number;
  baths: number;
  /** Size in square metres. */
  size: number;
  tag: string;
  exclusive: boolean;
  image: string;
  alt: string;
}

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=1000&auto=format&q=80`;

export const MERIDIAN_PROPERTIES: MeridianProperty[] = [
  {
    ref: "MR-047",
    name: "Sauk Hilltop",
    nameTail: "Villa",
    location: "Sauk i Ri, Tiranë",
    city: "Tiranë",
    status: "For Sale",
    type: "Villa",
    price: 138000,
    priceLabel: "€138,000",
    beds: 4,
    baths: 3,
    size: 320,
    tag: "Garden",
    exclusive: true,
    image: img("1564013799919-ab600027ffc6"),
    alt: "Three-storey villa in Sauk i Ri with garden",
  },
  {
    ref: "MR-052",
    name: "Blloku",
    nameTail: "Penthouse",
    location: "Blloku, Tiranë",
    city: "Tiranë",
    status: "For Sale",
    type: "Penthouse",
    price: 119000,
    priceLabel: "€119,000",
    beds: 3,
    baths: 2,
    size: 185,
    tag: "City view",
    exclusive: false,
    image: img("1600210492493-0946911123ea"),
    alt: "Top-floor penthouse in Blloku with skyline view",
  },
  {
    ref: "MR-031",
    name: "Lungomare",
    nameTail: "Apartment",
    location: "Lungomare, Vlorë",
    city: "Vlorë",
    status: "For Sale",
    type: "Apartment",
    price: 74000,
    priceLabel: "€74,000",
    beds: 2,
    baths: 2,
    size: 120,
    tag: "Sea view",
    exclusive: false,
    image: img("1600596542815-ffad4c1539a9"),
    alt: "Modern apartment in Lungomare Vlorë with sea view",
  },
  {
    ref: "MR-019",
    name: "Ksamil Beachfront",
    nameTail: "Villa",
    location: "Ksamil, Sarandë",
    city: "Sarandë",
    status: "For Sale",
    type: "Villa",
    price: 199000,
    priceLabel: "€199,000",
    beds: 5,
    baths: 4,
    size: 380,
    tag: "Beachfront",
    exclusive: true,
    image: img("1512917774080-9991f1c4c750"),
    alt: "Beachfront villa in Ksamil with white walls and pool",
  },
  {
    ref: "MR-068",
    name: "Liqeni i Thatë",
    nameTail: "Residence",
    location: "Liqeni i Thatë, Tiranë",
    city: "Tiranë",
    status: "For Rent",
    type: "Apartment",
    price: 480,
    priceLabel: "€480",
    beds: 3,
    baths: 2,
    size: 165,
    tag: "Furnished",
    exclusive: false,
    image: img("1600585154340-be6161a56a0c"),
    alt: "Modern apartment in Liqeni i Thatë",
  },
  {
    ref: "MR-074",
    name: "Durrës Marina",
    nameTail: "Loft",
    location: "Plazh, Durrës",
    city: "Durrës",
    status: "For Sale",
    type: "Apartment",
    price: 62000,
    priceLabel: "€62,000",
    beds: 2,
    baths: 2,
    size: 110,
    tag: "Port view",
    exclusive: false,
    image: img("1505691938895-1758d7feb511"),
    alt: "Modern marina-front loft in Durrës",
  },
  {
    ref: "MR-082",
    name: "Tirana e Re",
    nameTail: "Apartment",
    location: "Tirana e Re, Tiranë",
    city: "Tiranë",
    status: "For Sale",
    type: "Apartment",
    price: 49000,
    priceLabel: "€49,000",
    beds: 2,
    baths: 1,
    size: 92,
    tag: "Balcony",
    exclusive: false,
    image: img("1502672260266-1c1ef2d93688"),
    alt: "Bright apartment interior in Tirana e Re",
  },
  {
    ref: "MR-029",
    name: "Plazh Iliria",
    nameTail: "Townhouse",
    location: "Iliria, Durrës",
    city: "Durrës",
    status: "For Sale",
    type: "Townhouse",
    price: 86000,
    priceLabel: "€86,000",
    beds: 3,
    baths: 2,
    size: 175,
    tag: "Garden",
    exclusive: false,
    image: img("1570129477492-45c003edd2be"),
    alt: "Townhouse with garden near the Durrës coast",
  },
  {
    ref: "MR-091",
    name: "Radhimë Cliff",
    nameTail: "House",
    location: "Radhimë, Vlorë",
    city: "Vlorë",
    status: "For Sale",
    type: "Villa",
    price: 165000,
    priceLabel: "€165,000",
    beds: 4,
    baths: 3,
    size: 290,
    tag: "Sea view",
    exclusive: true,
    image: img("1613490493576-7fde63acd811"),
    alt: "Cliffside house above the Ionian near Radhimë",
  },
  {
    ref: "MR-104",
    name: "Borsh Coastal",
    nameTail: "Villa",
    location: "Borsh, Sarandë",
    city: "Sarandë",
    status: "For Sale",
    type: "Villa",
    price: 175000,
    priceLabel: "€175,000",
    beds: 4,
    baths: 4,
    size: 310,
    tag: "Pool",
    exclusive: false,
    image: img("1600047509807-ba8f99d2cdde"),
    alt: "Coastal villa with pool near Borsh",
  },
  {
    ref: "MR-058",
    name: "Blloku",
    nameTail: "Studio",
    location: "Blloku, Tiranë",
    city: "Tiranë",
    status: "For Rent",
    type: "Studio",
    price: 280,
    priceLabel: "€280",
    beds: 1,
    baths: 1,
    size: 48,
    tag: "Furnished",
    exclusive: false,
    image: img("1568605114967-8130f3a36994"),
    alt: "Compact furnished studio in Blloku, Tiranë",
  },
  {
    ref: "MR-063",
    name: "Ksamil Sea",
    nameTail: "Apartment",
    location: "Ksamil, Sarandë",
    city: "Sarandë",
    status: "For Rent",
    type: "Apartment",
    price: 350,
    priceLabel: "€350",
    beds: 2,
    baths: 1,
    size: 85,
    tag: "Sea view",
    exclusive: false,
    image: img("1600607687939-ce8a6c25118c"),
    alt: "Seaside apartment interior in Ksamil",
  },
];

